### ISSUE TITLE
在https://github.com/lagoueduCol/Algorithm-Dryad/blob/main/03.HeapAndPriorityQueue/347.%E5%89%8D-k-%E4%B8%AA%E9%AB%98%E9%A2%91%E5%85%83%E7%B4%A0.java中

### ISSUE THREAD

**Issue by XiangYouO** [lagoueduCol/Algorithm-Dryad#1]
代码不符合题目要求
测试数据：{3,3,4,1,1,1,2,2,3,5,5,5} 输出[1,5] 而不是[1,3]
在hashmap遍历添加时的顺序：
Node{val=1, cnt=3}
Node{val=2, cnt=2}
Node{val=3, cnt=3}
Node{val=4, cnt=1}
Node{val=5, cnt=3}
你可以用大堆，直接取出前k个top数；

int[] ans = new int[k];
        int j = 0;
        Queue<Node> nodes = new PriorityQueue<>((n1, n2) -> n2.cnt - n1.cnt);//小堆 比较的是次数
        for (Map.Entry<Integer, Integer> entry : map.entrySet()) {
            Node node =new Node(entry.getKey(), entry.getValue());
//            System.out.println(node);
            nodes.offer(node);
            if (nodes.size() > k&&j<k) {
                ans[j++] = nodes.poll().val;
            }
        }

**Comment by songwenju** [comment]
@XiangYouO 测试题目有说明啊，题目数据保证答案唯一，换句话说，数组中前 k 个高频元素的集合是唯一的

**Comment by XiangYouO** [comment]
好
